### ISSUE TITLE
Unity doesn't like its materials

### ISSUE THREAD

**Issue by TomOR1** [MicroGSD/RoadArchitect#1]
So I have opened the zip and dragged and dropped it into unity 3d, and none of the materials work. Some of the road materials are pink, and then others like the bridge materials are white. This is incredibly annoying, and even once I have re-assigned some of the textures it still isn't great. Please help. For debug purposes, I am running Unity 5.5.0f3 personal, and I have even tried importing it into an empty project and still no luck.

**Comment by Wezhayw** [comment]
^ i'm also experienced this. I found that all the files must be put into a folder called "RoadArchitect" (case-sensitive) within your projects Assets folder. Simply removing the "-master" in the folder name fixes a lot of stuff, the minority of materials work, aswell as the GUI elements. 
This however still has a few broken materials - linked to wrong or missing shaders, and barriers, lights, signs do not show etc.

**Comment by TomOR1** [comment]
@Wezhayw This didn't work for me. 

Wach this video I made:

https://drive.google.com/file/d/0B_CZzz4M1KKCNkowQVkxRVFRcGs/view?usp=sharing

**Comment by Wezhayw** [comment]
If you have the patience and really badly want to use, all materials are using textures of the same name. Use the GSD/Roads/Road shader, and if a material only has one texture then use GSD/TranShadowMarker shader

Some meshes aren't working properly and they need to be added to the prefabs of the same name

**Comment by MicroGSD** [comment]
I'll adjust the GitHub project to start with a RoadArchitect folder to make it more clear how to move it into the assets folder for a unity project. Can download release or clone the github project, unzip it. Consider it your local repo, and copy and paste into a /RoadArchitect directory in your assets folder.

I'll check out some of the assets and see which ones are having material issues. Post the names of the assets if you see any bugged ones.

**Comment by TomOR1** [comment]
@MicroGSD Don't you think it would be easier to just include a unity package into the repository so then it just imports it as if you had bought it when you had it on the asset store??

**Comment by TomOR1** [comment]
Like the one you put on the asset store

**Comment by TomOR1** [comment]
@MicroGSD Also none of the meshes work, I think if you add another branch wich has the unitypackage will be the best thing.

**Comment by Balgam** [comment]
@MicroGSD 

> Can download release or clone the github project, unzip it. Consider it your local repo, and copy and paste into a /RoadArchitect directory in your assets folder.

Hmm for me this also doesn't work still all materials are broken.

**Comment by Balgam** [comment]
@MicroGSD 

> Can download release or clone the github project, unzip it. Consider it your local repo, and copy and paste into a /RoadArchitect directory in your assets folder.

Hmm for me this also doesn't work still all materials are broken.
