### ISSUE TITLE
Big issue

### ISSUE THREAD

**Issue by AnnoyoingGamerz** [MicroGSD/RoadArchitect#10]
It seems that you have gave up on Road Architect I've literally been using this asset from the day it released on the asset store. I am extremely sad the the product is starting to bug out on Unity 5.6 I would like to help you get this asset back on track I know we can make this asset work and expand. I would really hate to see this asset go, please respond my email address is caleb@caleblawrence.com
I hope we can figure something out

**Comment by tonygod** [comment]
people ARE still working on it -- take a look at the github activity.  what are the specific issues you are having?  why not file those (and be specific) and maybe someone will take a look.  if you're up for a challenge, try to fix it yourself and submit a pull request so others can benefit from the same fix.

**Comment by AnnoyoingGamerz** [comment]
Sorry
I had never known how GitHub worked.
I just recently found out the basic, even though this site really is not hard to use...
I found R.A Release 1.6 today, and I would say, I am slapping my self in the face right now for not looking around earlier...
Damn, sorry for being that Annoying kid...
I wish I knew how to program better than I would help any way I could. And I still do what to help
Holy Damn, I Still love this asset to "Bits" Literally
