### ISSUE TITLE
Support for driving on the left side

### ISSUE THREAD

**Issue by YeshanJay** [MicroGSD/RoadArchitect#11]
Does 'Unity - Road Architect' support driving on the left side? If not, it would be really great if it did.
I'm trying to develop a racing game which drives on the left side of the road.

My problem occurs when it comes to intersections, where the stop signs and lines are on the other side (right).

**Comment by djohns451** [comment]
It doesn't support it currently, but I can explore implementing it.

**Comment by YeshanJay** [comment]
Thank you very much @djohns451  😄 
It would be really great if it's implemented.

**Comment by djohns451** [comment]
Major portions of the code need to be rewritten to support this.

**Comment by YeshanJay** [comment]
Yeah, I thought so. 🙁 
For now I'm inverting the whole road system game object after placing them, which is really tricky and not a good practice.

Inverting the roads means I'll have to invert each and every stop sign too or anything that has text, otherwise they'll be mirrored.

I'll try to manage it though, lol

**Comment by YeshanJay** [comment]
Any updates or thoughts on this? 
Any hope for this feature to be implemented in the future? 😄😬

**Comment by FritzsHero** [comment]
If you could make a list what is necessary for driving on the left side of the road, regarding this road system, I would be happy to help you.
I can probably even implement it as a addition to the current stable release, what version do you currently use? 1.6 or 1.7 or 1.9

**Comment by YeshanJay** [comment]
Hi @FritzsHero 

I guess the first thing would be to render the lane stop marks on the left, and the signs and arrows too.

Will be using the latest version (btw, is 1.9 released yet?).

Thanks mate.
