### ISSUE TITLE
GSD/TranShadow shader: v2f missing semantic for lightDir in ShadowPass [2017.1.0xf1]

### ISSUE THREAD

**Issue by mneilly** [MicroGSD/RoadArchitect#18]
Unity 2017 reports the following error and fails to compile Shaders/GSDTransparentWithShadows.shader due to a missing semantic on lightDir.

> Shader error in 'GSD/TranShadow': 'frag': input parameter 'i' missing semantics at line 118 (on glcore)
> 
> Compiling Vertex program with DIRECTIONAL
> Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_COLORSPACE_GAMMA UNITY_LIGHT_PROBE_PROXY_VOLUME
> 

Adding the semantic resolves the compile problem:

```
diff --git a/Shaders/GSDTransparentWithShadows.shader b/Shaders/GSDTransparentWithShadows.shader
index 69ac7bc..c749025 100644
--- a/Shaders/GSDTransparentWithShadows.shader
+++ b/Shaders/GSDTransparentWithShadows.shader
@@ -94,7 +94,7 @@ ENDCG
                                float2 uv_MainTex : TEXCOORD1;
                                float4 pos : SV_POSITION;
                                LIGHTING_COORDS(3,4)
-                               float3  lightDir;
+                               float3  lightDir : TEXCOORD2;
                        };

                        float4 _MainTex_ST;

```

**Comment by djohns451** [comment]
This will be irrelevant soon because of #12.
