### ISSUE TITLE
New system for road decals and road decal placement.

### ISSUE THREAD

**Issue by djohns451** [MicroGSD/RoadArchitect#20]

**Comment by gsdnano** [comment]
See comment here: https://github.com/MicroGSD/RoadArchitect/issues/21#issuecomment-314452778

Any thoughts anyone?

**Comment by djohns451** [comment]
On the concept of potholes and the like, that would be a near perfect application of a normal map, assuming there would not need to be any interaction or dynamic modification. If so, a normal mapped mesh would do the trick just fine.

**Comment by djohns451** [comment]
You'll need some sort of splatmap internally, because the direction Unity's going in is in multiple shader passes instead of multiple materials. As such, you'll need to shift off the computation of the location of such features to the GPU, especially with a solution similar to a compute shader.

**Comment by tonygod** [comment]
For potholes, you could just use standard shader and PBS Materials.  Occlusion Layer for proper shadowing and as @djohns451 pointed out, a normal map and you would want to use other maps for up close details, specular for wetness/shinyness.

**Comment by djohns451** [comment]
A normal mapped solution would allow for lightweight dynamic tessellation,
too.
