### ISSUE TITLE
Better system for road lines.

### ISSUE THREAD

**Issue by djohns451** [MicroGSD/RoadArchitect#21]

**Comment by gsdnano** [comment]
Somewhat related, some thoughts on decals.

GTAV's heavy use of decals for almost all aspects of their road systems is impressive from a performance and detail perspective. Manhole covers, road patches,  potholes, lane markings etc.

Eventually it would be nice to convert RA to use decals for markings + add the other items like road patches / potholes / lane markings etc (with options for randomized / clustered placement). Collision zones on the road for some of these objects would be nice for sounds etc.

This would also have the benefit of allowing the user to plug in their own decals easily, to help our many government users to adhere to US / EU / State regulation and specs on lane markings.

However it could prove quite difficult with z fighting and road elevation changes.  I'm sure a mesh system for potholes / manhole covers etc is doable but probably not great for performance.

**Comment by MCrafterzz** [comment]
If you make a model for a manhole cover and rotate it as much as the road is tilted woudn't that fix the the elevation issue? To fix the z fighting you could change the sorting order of the mesh renderer which is accesable with code.

**Comment by djohns451** [comment]
See issue #21.
