### ISSUE TITLE
Intersections between 2 and 4 lane roads have gaps and other issues

### ISSUE THREAD

**Issue by tonygod** [MicroGSD/RoadArchitect#23]
If you intersect a 2-lane road with a 4-lane road, the resulting intersection shows stopping lines for the 2-lane road in the middle of the intersection and there is texture z-order layering issues.

If you intersect a 4-lane road with a 2-lane road, the resulting intersection has large gaps.

[See this video for an illustration of what happens in both cases](https://www.youtube.com/watch?v=LMaEtfLsSZg)

**Comment by djohns451** [comment]
@tonygod Fixed a bad video link in the comment above.

**Comment by tonygod** [comment]
The changes for this probably need to go somewhere in GSDRoadUtilityT.cs GSDRoadCreationT.RoadJob_Prelim_Inter when setting the four intersection corner points.  

I have been able to alter the intersection size by using combinations of road separation values when setting PreInterVectR and PreInterVectL for both nodes, and I can get close to the desired mesh, but something later in the code is resetting the points, so the final mesh isn't forming properly.

This function is a monster and could use a lot more comments to help figure out what is going on.  I spent many hours digging, but I have not yet found ALL of the code that needs changing, just some of it.

**Comment by djohns451** [comment]
@tonygod I'll add the details to a project board and spend some time digging on my own.

@MicroGSD could probably help a lot with this.

**Comment by djohns451** [comment]
> This function is a monster

It sounds like it needs to be broken down.

**Comment by djohns451** [comment]
@tonygod `GSDRoadCreationT.RoadJob_Prelim()` looks just as bad, something like 1500 SLOC. I'm working on refactoring it to add support for banked turns, but I can look into that function too.

**Comment by tonygod** [comment]
Whatever you can do, I appreciate and support.  It's a difficult problem to get just right and yet it's so important because of all the real-world examples of non-uniform intersections.
