### ISSUE TITLE
RoadArchitect menu does not appear on toolbar to create a Road System

### ISSUE THREAD

**Issue by desireend** [MicroGSD/RoadArchitect#24]

**Comment by djohns451** [comment]
@desireend Can you provide a screenshot of the toolbar and the relevant portions of your Project log?

**Comment by desireend** [comment]
![image](https://user-images.githubusercontent.com/22029278/28040058-79ba9fb4-6592-11e7-8ee5-4eeb2483cad3.png)

**Comment by djohns451** [comment]
@desireend Check for errors in the [Console](https://docs.unity3d.com/Manual/Console.html) below.

**Comment by desireend** [comment]
I corrected the errors and it still does not show.

**Comment by gsdnano** [comment]
Which toolbar are you referring to? The menu toolbar? Check the "Window" menu item, iirc.

Unity changed their policy on the menu system for assets the day before RA was submitted and I was forced to change it at the last moment, so some of the documentation and videos refers to the RA menu being its own primary menu item.

**Comment by djohns451** [comment]
I can't reproduce the error on my end.

**Comment by desireend** [comment]
I see the menu system under window. Thank you.
