### ISSUE TITLE
Remove references to deprecated libraries.

### ISSUE THREAD

**Issue by djohns451** [MicroGSD/RoadArchitect#27]
Which libraries in particular?

**Comment by gsdnano** [comment]
Referencing some internal libraries from 4 years ago in the traffic code. Going to remove them before the initial code upload for the traffic stuff.

**Comment by djohns451** [comment]
@gsdnano When can we expect the initial code upload?

**Comment by djohns451** [comment]
@gsdnano Any update? We can clean up the code, if need be.
