### ISSUE TITLE
Decide on separate @next branch to avoid issues on the traffic system during early implementation phase vs just putting it in dir with warning for consumers

### ISSUE THREAD

**Issue by djohns451** [MicroGSD/RoadArchitect#28]

**Comment by djohns451** [comment]
It might be better to tag the releases and keep the master branch for live (and unstable) code.

**Comment by gsdnano** [comment]
I like that idea, let's do that.

**Comment by djohns451** [comment]
Note that this is the recommended practice with git anyway.

**Comment by djohns451** [comment]
If it's planned to have primary functionality, the traffic code would be best spun off into a new Git repository.
