### ISSUE TITLE
Extract testing code from menu system.

### ISSUE THREAD

**Issue by djohns451** [MicroGSD/RoadArchitect#29]

**Comment by djohns451** [comment]
@gsdnano Does this apply to this repo or the traffic code?

**Comment by FritzsHero** [comment]
What exactly is this about?
And where is this so called "Traffic system"?
An answer from former maintainers would be great, otherwise we can close this issue down I guess.

**Comment by embeddedt** [comment]
There was a traffic system that was never publicly released, because (from what I read) it was rather unstable.

**Comment by djohns451** [comment]
MicroGSD, now gsdnano, is the only one with access to source code of that
traffic system project.
