### ISSUE TITLE
Materials do not work with Unity 5.6.0f3

### ISSUE THREAD

**Issue by djohns451** [MicroGSD/RoadArchitect#3]

**Comment by TomOR1** [comment]
use the unity package:
https://github.com/MicroGSD/RoadArchitect/releases

**Comment by TomOR1** [comment]
and close the issue

**Comment by djohns451** [comment]
@TomOR1 The attached Release package suffers from the same issues.

**Comment by mneilly** [comment]
The materials do not work from Git because the .meta files are not included and are included in the .gitignore file erroneously. 

Per the Unity documentation:
(https://docs.unity3d.com/Manual/ExternalVersionControlSystemSupport.html)
> Before checking your project in, you have to tell Unity to modify the project structure slightly to make it compatible with storing assets in an external version control system. **_This is done by selecting Edit->Project Settings->Editor in the application menu and enabling External Version Control support by selecting Visible Meta Files in the dropdown for Version Control._** This will show a text file for every asset in the Assets directory containing the necessary bookkeeping information required by Unity. The files will have a .meta file extension with the first part being the full file name of the asset it is associated with. Moving and renaming assets within Unity should also update the relevant .meta files. However, if you move or rename assets from an external tool, make sure to syncronize the relevant .meta files as well.
> 
> **_When checking the project into a version control system, you should add the Assets and the ProjectSettings directories to the system._** The Library directory should be completely ignored - when using .meta files, it’s only a local cache of imported assets.
> 
> **_When creating new assets, make sure both the asset itself and the associated .meta file is added to version control._**

**Comment by djohns451** [comment]
@mneilly Since we release as a unitypackage, adding .meta files would prove a hindrance to making sure that the items import properly as-is.

**Comment by djohns451** [comment]
Trying with a fresh installation, the Materials work.
