### ISSUE TITLE
One lane road (Started working on it but need help)

### ISSUE THREAD

**Issue by MCrafterzz** [MicroGSD/RoadArchitect#31]
One way roads would really be great for hightway ramps etc.

I have started working on it, see progress here:
https://github.com/MCrafterzz/RoadArchitect

It does work on roads without intersection and with all road materials. It doesn't work with intersection tho which is what I need help with. It needs more assets for intersection which I don't know how they should look.

**Comment by djohns451** [comment]
Which intersection are you referring to? The standard Stop Sign model and Traffic Light models look to be compatible with the your code, superficially.

**Comment by MCrafterzz** [comment]
http://imgur.com/a/kqQ95
The one to the left is a 1-1 road intersection. Gives save result both with normal and stop signs. Traffic lights make it crash:
IndexOutOfRangeException: Array index is out of range.
GSDTrafficLightController..ctor (UnityEngine.GameObject& _LightLeft, UnityEngine.GameObject& _LightRight, UnityEngine.GameObject[]& _Lights, UnityEngine.MeshRenderer& _MR_Left, UnityEngine.MeshRenderer& _MR_Right, UnityEngine.MeshRenderer[]& MR_Mains) (at Assets/RoadArchitect/GSDTrafficLightController.cs:52)
GSD.Roads.GSDIntersectionObjects.ProcessPole (UnityEngine.GameObject MasterGameObj, UnityEngine.GameObject tObj, Vector3 tan, Int32 tCorner, Single InterDist) (at Assets/RoadArchitect/GSDRoadUtility.cs:5046)
GSD.Roads.GSDIntersectionObjects.CreateTrafficLightMains (UnityEngine.GameObject MasterGameObj, UnityEngine.GameObject tRR, UnityEngine.GameObject tRL, UnityEngine.GameObject tLL, UnityEngine.GameObject tLR) (at Assets/RoadArchitect/GSDRoadUtility.cs:4849)
GSD.Roads.GSDIntersectionObjects.CreateTrafficLightBases_Do (UnityEngine.GameObject& MasterGameObj, Boolean bIsTrafficLight1) (at Assets/RoadArchitect/GSDRoadUtility.cs:4654)
GSD.Roads.GSDIntersectionObjects.CreateTrafficLightBases (UnityEngine.GameObject MasterGameObj, Boolean bIsTrafficLight1) (at Assets/RoadArchitect/GSDRoadUtility.cs:4447)
GSD.Roads.RoadConstructorBufferMaker.MeshSetup1_IntersectionObjectsSetup () (at Assets/RoadArchitect/GSDRoadUtility.cs:1526)
GSD.Roads.RoadConstructorBufferMaker.MeshSetup1_Do () (at Assets/RoadArchitect/GSDRoadUtility.cs:1406)
GSD.Roads.RoadConstructorBufferMaker.MeshSetup1 () (at Assets/RoadArchitect/GSDRoadUtility.cs:1396)
GSDRoad.ConstructRoad3 () (at Assets/RoadArchitect/GSDRoad.cs:711)
GSDRoad.EditorUpdate () (at Assets/RoadArchitect/GSDRoad.cs:219)
GSDRoad.<OnEnable>m__0 () (at Assets/RoadArchitect/GSDRoad.cs:138)
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at C:/buildslave/unity/build/Editor/Mono/EditorApplication.cs:127)

The one to the right is a one with turn lane which has a totally wrong texture but that one I proberly can fix my self.
