### ISSUE TITLE
Intersections are really bugged out

### ISSUE THREAD

**Issue by MCrafterzz** [MicroGSD/RoadArchitect#32]
http://imgur.com/a/Urd6S

**Comment by djohns451** [comment]
All uneven intersections suffer from this issue, since the code assumes
intersections are square.

See issue #23 for updates on this.

**Comment by MCrafterzz** [comment]
Ok

**Comment by MCrafterzz** [comment]
There are some other problems to like that the edge objects go right throught the intersection. Also here is a two lane road that has more a bunch more lanes before the intersection http://imgur.com/a/1gsHe
