### ISSUE TITLE
Creating new nodes clears selected materials. 

### ISSUE THREAD

**Issue by Shizola** [MicroGSD/RoadArchitect#38]
Every time I place a new node my road base material gets set to none and I get a pink road. Using Unity 2017.1  Any Ideas?

**Comment by djohns451** [comment]
Is this while using a release or a git clone?

**Comment by Shizola** [comment]
git clone

**Comment by Shizola** [comment]
just found the unity package in the release section, works fine.

**Comment by gsdnano** [comment]
The solution was to use the release version https://github.com/MicroGSD/RoadArchitect/releases instead of the git clone version.
