### ISSUE TITLE
Support for Highways/Turnpikes 

### ISSUE THREAD

**Issue by Claw57** [MicroGSD/RoadArchitect#42]
I think a neat addition for R.A would be a Highway Integration!
Of course, a Highway Integration would be a big project! from customizable space in between Highway Sides to Ramps, tollbooths, and Lanes!
I Think there could be another Catagory for highway Nodes, From Exit Signs, and Gaurd Rails, to Lampost and, Overhead Signs.
Another Idea for Highways is a Tollbooth Entrance, you can select a Node, and there could be a check mark for Tollbooth or nonPaid Entrance 

I Think this could be a great integration, and lots of people I brought it up to in the past agree!

I could help design Tollbooths, and Lampost, and whatever you need!
What do you guys think? Good idea for release 2, or maybe later?

**Comment by djohns451** [comment]
@AnnoyoingGamerz I'd suggest starting with the meshes, as code integration can take quite some time.

**Comment by djohns451** [comment]
@AnnoyoingGamerz I'll take a look to see what needs to be done to separate the sides.

**Comment by AnnoyoingGamerz** [comment]
@djohns451 Sweet Ill start on the Meshes!!
When I am done is there a way I can send them to you?
Google Drive or something else?

**Comment by djohns451** [comment]
Commit them to your repository, I'll see how we can integrate them.
