### ISSUE TITLE
Update Release 

### ISSUE THREAD

**Issue by aammfe** [MicroGSD/RoadArchitect#44]
Hello!

Please update release package. 
![image](https://user-images.githubusercontent.com/11896817/37134668-5bcbaf7a-22bb-11e8-9fd9-a1534ef2ea10.png)

If I directly download this repo materials looses texture references.

![image](https://user-images.githubusercontent.com/11896817/37134759-cfecbe62-22bb-11e8-9580-4c4eb28cadd3.png)

**Comment by djohns451** [comment]
@aammfe The code in the `master` branch isn't production ready. For general consumption, use the .unitypackage listed.
