### ISSUE TITLE
Closed loop Road

### ISSUE THREAD

**Issue by aammfe** [MicroGSD/RoadArchitect#45]
Hello How could I use this plugin to make some thing like this.

![image](https://user-images.githubusercontent.com/11896817/37135978-6ec0edc4-22c1-11e8-99f6-5f40329e42d2.png)

but I could not make it closed.
![image](https://user-images.githubusercontent.com/11896817/37136938-819078a8-22c5-11e8-910a-ee7eb65a20c8.png)

Its a close loop road it has other details too.

**Comment by tonygod** [comment]
As of right now you have to create your own custom gap-filler.  You can use planes, cubes, cylinders or make custom meshes with ProBuilder to fill in these gaps.  I hope one day there will be improved support for closed loops.

**Comment by embeddedt** [comment]
@aammfe My fork should handle this now: https://github.com/embeddedt/RoadArchitect.

**Comment by embeddedt** [comment]
If you have problems with closed loops please open an issue on my fork.
