### ISSUE TITLE
Road Detailing Issue 

### ISSUE THREAD

**Issue by aammfe** [MicroGSD/RoadArchitect#46]
Hello!

Thanx for this gorgeous plugin , 

I m having detailing issue with road.
when ever I run car over it seems like its is raveling its details as I travel  on.

![image](https://user-images.githubusercontent.com/11896817/37136841-1cf20cae-22c5-11e8-81a9-b8e709b74434.png)

**Comment by djohns451** [comment]
That is an issue with the Standard shader that we're looking into.
