### ISSUE TITLE
Access Spline Tangent and relevant position along spline for a given t value

### ISSUE THREAD

**Issue by deltamish** [MicroGSD/RoadArchitect#47]
Hey,

I am trying to simulate an AI Car. The car needs to reset to a position along the track where it last got off (Like NFS games where once you crash you respawn to nearest point on the track)
And the car needs to orient in same direction facing the road ahead 

Any idea or pointers on how I would go about it 

Thanks

**Comment by lb28** [comment]
I also am trying to access the position along the track, as I want a car to follow the track (without a waypoint system). @deltamish have you figured out a way? I haven't yet looked into all the code, but it has to be in there somehwere, the street is drawn somehow after all...

**Comment by deltamish** [comment]
Hey,
There wasn't anything available inbuilt as such or maybe I didn't dig deep enough. So decided to use an external [BezierSpline ](https://github.com/yasirkula/UnityBezierSolution)Curve that gets placed along with the Spline Nodes of road architect. 

The BezierSpline solution has a very good and detailed API calls available. Link FindNearestPoinTo,Move along etc. 
Its a cheap hack for little effort and time.

**Comment by lb28** [comment]
Hey, thanks for the info! One more thing: Did you have to manually draw the Bezier Curves along the route?

**Comment by embeddedt** [comment]
@flibblesbane Not sure if you are still using RoadArchitect but I am working on making simple traffic work and I am removing some unnecessary `#if UNITY_EDITOR` along the way.

If you're interested have a look at https://github.com/embeddedt/RoadArchitect. Please note that it's not production-ready software.

**Comment by kinetixx** [comment]
try for position and rotation:
`Vector3 v1, v2;
spline.GetSplineValue_Both(Mathf.PingPong(Distance, 1f), out v1, out v2);
this.transform.localPosition = v1;
this.transform.localRotation = Quaternion.LookRotation(v2);`
