### ISSUE TITLE
T-Junction

### ISSUE THREAD

**Issue by botiapa** [MicroGSD/RoadArchitect#48]
Can I create a T-junction with RoadaRchitect? Any help would be appreciated.

**Comment by botiapa** [comment]
How could I fix that?

**Comment by ArtyIF** [comment]
This is a known issue. It's been there forever.

**Comment by djohns451** [comment]
Yeah, it's something we're working on, but so far the code assumes the
intersection is between roads of equal lane counts.

**Comment by botiapa** [comment]
Then, is there any workaround to this?

**Comment by ArtyIF** [comment]
well you can connect the ends of roads with different count of lanes. create a 4-lane road, make an intersection with another one and then connect the ends with 2-lane oneOn May 5, 2018 20:34, killswitch <notifications@github.com> wrote:Then, is there any workaround to this?

**Comment by djohns451** [comment]
Yeah, that works for now, it's a bit of a hack, though.

**Comment by botiapa** [comment]
Okay, thanks for the help. I don't know if I should close this issue, as it isn't fixed. I think it's better if I leave this choice to the admin.

**Comment by tonygod** [comment]
This is a duplicate of #23
