### ISSUE TITLE
Creating Roads via Code 

### ISSUE THREAD

**Issue by deltamish** [MicroGSD/RoadArchitect#49]
Hey,

Q1.) Is there any way where the rods can be created via code. If so can you provide some example on hough to place the Road Points and also define the type of road. 

Q2.) Is it possible to create roads at runtime ? 

Thanks

**Comment by anpd03** [comment]
Also interested in this, anyone that have done it?

**Comment by tonygod** [comment]
the best place for questions is on the forum -- the github issues area is for reporting bugs or requesting features.

[https://forum.unity.com/threads/road-architect-roads-intersections-and-bridges-for-unity-released.232335](https://forum.unity.com/threads/road-architect-roads-intersections-and-bridges-for-unity-released.232335)

RoadArchitect appears to be designed to only construct roads in the editor.  It would take significant refactoring to get it to work in runtime.
