### ISSUE TITLE
import RoadArchitect-master to unity

### ISSUE THREAD

**Issue by ptcriuer** [MicroGSD/RoadArchitect#50]
I want to know how to install this package into unity?

**Comment by tonygod** [comment]
you should ask these questions on the forum.  this is where you should report specific bugs.

[https://forum.unity.com/threads/road-architect-roads-intersections-and-bridges-for-unity-released.232335](https://forum.unity.com/threads/road-architect-roads-intersections-and-bridges-for-unity-released.232335)

You import the package just like any other custom unity package:  Assets->Import Package->Custom Package...
