### ISSUE TITLE
not working in unity 2018.2

### ISSUE THREAD

**Issue by hemanth2410** [MicroGSD/RoadArchitect#51]
Installed through unity package but road architect menu didnot appear

**Comment by tonygod** [comment]
A couple of API changes in Unity 2018 cause compile errors in a couple of scripts.  There appear to be a couple of other issues as well that I am trying to track down.

**Comment by embeddedt** [comment]
@hemanth2410 Please try https://github.com/embeddedt/RoadArchitect.
