### ISSUE TITLE
Road Quality

### ISSUE THREAD

**Issue by zezo010** [MicroGSD/RoadArchitect#55]
When using this asset with new Unity 208.2 , I found that the road quality is very bad and the road can't be seen good from above !!
I wish that if there any way to change road texture ( Asphalt ) to any texture i choose

**Comment by mchrbn** [comment]
Had the same issue for the marking lines of my road it's because of Unity settings. I solved it by:
1) Make sure that Anisotropic Textures is on Forced On in Quality Settings
2) Select all textures in Materials/Markers/Textures and disable Generate Mip Maps in Advanced settings

**Comment by zezo010** [comment]
But it will affect on other tools and scripts used in the project ?  i will give it a try

thanks

**Comment by djohns451** [comment]
The issue is because of Unity's texture settings. I'll see if I can find
the relevant steps to follow in the Gitter chat room set up for the project.

**Comment by zezo010** [comment]
I tried this steps
https://github.com/MicroGSD/RoadArchitect/issues/55#issuecomment-410964098
above and i get it but it's very noisy :(

**Comment by djohns451** [comment]
@zezo010 What kind of noise are you getting? You may see some z-fighting, but increasing the "Terrain subtraction" can help in that regard.

**Comment by zezo010** [comment]
@djohns451 the lines and colors more sharply and affected on any object on it.

**Comment by djohns451** [comment]
@embeddedt, @zezo010 Marker textures now have a degree of anisotropic filtering applied, which should, for the most part, mitigate this effect.
