### ISSUE TITLE
Custom ShapeFile Road Network

### ISSUE THREAD

**Issue by PauloDeMello** [MicroGSD/RoadArchitect#58]
Hi,
I'm really interested in purchasing Real World Terrain to use with RoadArchitect.
My goal is to drape a shape file with traffic data over an elevation model of the UK.
I was wondering if there was a feature that would let me import the ShapeFile as a road network and visualize my point traffic data easily? If not, would I be able to do so within RoadArchitect / Real World Terrain?

Any help would be much appreciated.

Thanks,
Paulo

**Comment by embeddedt** [comment]
@PauloDeMello You cannot import road networks into RoadArchitect at this time.
