### ISSUE TITLE
Road markers splinate below the pavement mesh for roads with two nodes

### ISSUE THREAD

**Issue by ghost** [MicroGSD/RoadArchitect#59]
Sorry if this issue has been reported before but at some point the road markers stopped being applied to all roads and even after deleting/replacing relaunching unity they have not come back.  Any way I can get around this or force them back on? Even if I add the markers to the materials check the box and hit apply they don't show up. Not sure if it is related or not but when they were showing up they had a very very low stream distance.

**Comment by djohns451** [comment]
See #55 on the stream distance.

**Comment by Narcotic904** [comment]
Yeah that fixed the stream distance and for whatever reason the road has to have 3 nodes or more to render any road lines.

**Comment by zezo010** [comment]
@djohns451 the lines and colors more sharply and affected on any object on it.

**Comment by embeddedt** [comment]
OP's user account has been deleted and I fixed the issue in https://github.com/embeddedt/RoadArchitect/commit/8d185ec88b02e4b01d57c26d77acea8fd74d8479.
