### ISSUE TITLE
Applying a road segment modify inconsistently the terrain.

### ISSUE THREAD

**Issue by theshinyknight** [MicroGSD/RoadArchitect#60]
I noticed a strange behavior with terrain: when applying different road segments; instead than having the segment to comform to the terrain, the terrain is raised; causing a sort of platform below the road; while the expectation was that the road would sit almost flush on the terrain, using the offset value in the parameters to avoid Z-fighting.

Also the area around the road is affected; with the result that instead of creating a flat road; the terrain is carved on both sides of the road. Not sure if this is a bug or the expected behavior. From the videos, I can see that the terrain does not change, unless a node transform change in height.

Also if you reload a scene after that the terrain has been modified, the terrain is saved, so once you apply a road on the terrain, it is a one way road and the terrain changes are persistent, even if you didn't save the scene.

**Comment by embeddedt** [comment]
@theshinyknight 

Can you try to reproduce this issue on https://github.com/embeddedt/RoadArchitect?

> I noticed a strange behavior with terrain: when applying different road segments; instead than having the segment to comform to the terrain, the terrain is raised; causing a sort of platform below the road

Depending on how you are placing the road this is sometimes expected behavior.

> Also the area around the road is affected; with the result that instead of creating a flat road; the terrain is carved on both sides of the road. 

There is a height match width setting (I will get the exact name later) that you can reduce to keep this from being visible as much.

> Also if you reload a scene after that the terrain has been modified, the terrain is saved, so once you apply a road on the terrain, it is a one way road and the terrain changes are persistent, even if you didn't save the scene.

Try deleting the road one node at a time and see if the problem persists.
