### ISSUE TITLE
Bridge visible under road (mesh calculation error?)

### ISSUE THREAD

**Issue by embeddedt** [MicroGSD/RoadArchitect#61]
When creating a bridge by following the tutorial, the bottom of the bridge seems to project through the road.

![screenshot from 2018-10-27 16-07-52](https://user-images.githubusercontent.com/42941056/47608859-87ec4c00-da02-11e8-8092-9db7f33ea3ed.png)

Increasing `Terrain subtraction` did not help.

**Comment by embeddedt** [comment]
At the moment I can work around this by manually lowering the bridge bottom in the Unity Editor every time I move the node, but this is annoying.

**Comment by embeddedt** [comment]
A slightly better workaround: change vertical raise in the extrusion/edge object options. Still not ideal.

**Comment by MicroGSD** [comment]
Hi embeddedt,

- Can you please post a bigger screenshot? 
- My first thoughts there are to check the road grade.  Lots of times when I ran into that it was because I was using unrealistic road grades (which looked normal enough in the editor).
- What is the terrain resolution being used here?

**Comment by embeddedt** [comment]
@MicroGSD Yes, it was with a very steep road grade. I have noticed the problem doesn't occur when using low road grades. So maybe this isn't really a bug.

Nice to see that this project still has some activity!

**Comment by embeddedt** [comment]
@MicroGSD 

> I'm not even sure where RA is with the latest versions of Unity, hoping to get back into it soon.

That is GREAT news! I discovered RA recently and I was *really* impressed by the whole product (and the amazing sign/bridge quality, awesome job!), but some of the random bugs that occured (especially on Unity 2018) made me question whether it would be a good asset to rely on. I'd be glad to help with fixing stuff if you'd like, but I don't know anything about procedurally generating meshes so my help would be limited to GUIs, materials, stuff like that.

> Another issue with unrealistic road grades is it was difficult to program traffic to function properly. e.g. getting air on simple hills.

I don't think that's a major issue. Probably just mentioning that unrealistic road grades can have issues is suitable.

**Comment by embeddedt** [comment]
@MicroGSD Thanks for the invitation! I have a fork at https://github.com/embeddedt/RoadArchitect with some bugfixes/improvements. If you would like I can merge back my changes with a pull request.
