### ISSUE TITLE
Error message in Unity 2018.3 MacOS (RoadArchitect V1.7)

### ISSUE THREAD

**Issue by FelixCM** [MicroGSD/RoadArchitect#62]
Hi, I am new to RoadArchitect and super excited to get started with this tool!

Unfortunately I get the following error message when adding or inserting a new node on my terrain: 

> SerializationException: Unable to load type System.Collections.Generic.List`1[[GSD.Roads.GSDTerrainHistoryMaker, Assembly-CSharp-firstpass, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]] required for deserialization.
> System.Runtime.Serialization.ObjectManager.DoFixups () (at <ac823e2bb42b41bda67924a45a0173c3>:0)
> System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize (System.Runtime.Remoting.Messaging.HeaderHandler handler, System.Runtime.Serialization.Formatters.Binary.__BinaryParser serParser, System.Boolean fCheck, System.Boolean isCrossAppDomain, System.Runtime.Remoting.Messaging.IMethodCallMessage methodCallMessage) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
> System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize (System.IO.Stream serializationStream, System.Runtime.Remoting.Messaging.HeaderHandler handler, System.Boolean fCheck, System.Boolean isCrossAppDomain, System.Runtime.Remoting.Messaging.IMethodCallMessage methodCallMessage) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
> System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize (System.IO.Stream serializationStream, System.Runtime.Remoting.Messaging.HeaderHandler handler, System.Boolean fCheck, System.Runtime.Remoting.Messaging.IMethodCallMessage methodCallMessage) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
> System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize (System.IO.Stream serializationStream, System.Runtime.Remoting.Messaging.HeaderHandler handler, System.Boolean fCheck) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
> System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize (System.IO.Stream serializationStream, System.Runtime.Remoting.Messaging.HeaderHandler handler) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
> System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize (System.IO.Stream serializationStream) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
> GSD.Roads.GSDGeneralEditor.TerrainHistory_Load (GSDRoad tRoad) (at Assets/RoadArchitect/GSDRoadUtility.cs:3069)
> GSDRoad.ConstructRoad_LoadTerrainHistory (System.Boolean bForce) (at Assets/RoadArchitect/GSDRoad.cs:633)
> GSDRoad.UpdateRoad (GSD.Roads.RoadUpdateTypeEnum tUpdateType) (at Assets/RoadArchitect/GSDRoad.cs:410)
> GSDSplineC.Setup_Trigger () (at Assets/RoadArchitect/Spline/GSDSplineC.cs:69)
> GSDRoad.EditorUpdate () (at Assets/RoadArchitect/GSDRoad.cs:233)
> GSDRoad.<OnEnable>b__85_0 () (at Assets/RoadArchitect/GSDRoad.cs:138)
> UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at /Users/builduser/buildslave/unity/build/Editor/Mono/EditorApplication.cs:200)
> 

When adding another node using control I get the same error again and an out of bound error: 

> ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
> Parameter name: index
> System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
> System.ThrowHelper.ThrowArgumentOutOfRangeException () (at <ac823e2bb42b41bda67924a45a0173c3>:0)
> System.Collections.Generic.List`1[T].get_Item (System.Int32 index) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
> GSDSplineN.CanBridgeStart () (at Assets/RoadArchitect/Spline/GSDSplineN.cs:1019)
> GSDSplineNEditor.OnInspectorGUI () (at Assets/RoadArchitect/Editor/GSDSplineNEditor.cs:352)
> UnityEditor.InspectorWindow.DoOnInspectorGUI (System.Boolean rebuildOptimizedGUIBlock, UnityEditor.Editor editor, System.Boolean wasVisible, UnityEngine.Rect& contentRect) (at /Users/builduser/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1625)
> UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
> 

If I add a second node using shift+click Unity freezes and I have to force quit the application. 

I made sure that all the files are in a RoadArchitect folder in my assets and have not been modified. 

Any suggestions on how to fix this error?

Thanks in advance!

**Comment by FelixCM** [comment]
Update: If I move the RoadArchitect main folder into a sub-folder everything seems to be working fine except for that none of the materials are being found. I hope this helps resolving the issue.

**Comment by FritzsHero** [comment]
Hello FelixCM,

do you still have any problems with the code?
Yes, currently the "working" path is bound to some locations. One of them being "/Assets/RoadArchitect".
Placing all RoadArchitect stuff inside that folder should ensure everything is working as expected.

I will close this ticket. Feel free to reopen it or to create a new ticket, if you got any problem.


Greetings
Fritzs
