### ISSUE TITLE
Single RoadArchitectSystem Vs Multiple RoadArchitectSystem

### ISSUE THREAD

**Issue by MuhammadWaqasOfficial** [MicroGSD/RoadArchitect#65]
Using RA first time.
Need Suggestion.
Single RoadArchitectSystem for entire road system Or multiple RoadArchitectSystems for roads?

**Comment by embeddedt** [comment]
@MuhammadWaqasOfficial You should be able to use a single RoadArchitectSystem for all of your roads.

**Comment by MuhammadWaqasOfficial** [comment]
Okay Sir.
Thank you
