### ISSUE TITLE
Some Objects Not Being Displayed

### ISSUE THREAD

**Issue by anthonyromyn** [MicroGSD/RoadArchitect#69]
Hi RoadArchitect Team,

Great product, really like it. Thanks so much for making it. While using it I encountered a bit of strange behaviour, however, and I haven't been able to figure out how to fix it. 
1. When I load a prefab, the road and concrete divider don't load until I hit the update road button. Then, if I save and reload, the same behaviour occurs.
2. Then, when running the game we are building, we see that the same road and concrete divider objects aren't loading. I assume these are related, but haven't yet been able to solve.

Here is a link to a screen-recording showing the strange behaviour (https://vimeo.com/325892664). 

Some specifics:
MacOS 10.12.6 
Unity 2018.3.0f2
RoadArchitect is the current master branch (last updated Jan 22nd)

Thanks so much for any help and feedback!
Best,
Anthony

**Comment by embeddedt** [comment]
@anthonyromyn If it's not a lot of work, would you mind trying [my fork](https://github.com/embeddedt/RoadArchitect) to see if that has the same issue?

**Comment by anthonyromyn** [comment]
@embeddedt Hey thanks so much for the response. Tried out your fork, but same behaviour. Video is here in case it's of any help https://vimeo.com/326345898

**Comment by embeddedt** [comment]
@anthonyromyn Not sure if this is possible for you, but could you create a simple project that you can upload that reproduces the issue?

**Comment by anthonyromyn** [comment]
Woops sorry didn't mean to close this haha. Hmm yep will get back to you in a few!

**Comment by anthonyromyn** [comment]
Okay @embeddedt here's the software https://github.com/DuncanLab/RoadRAGE. If you could try building a RoadArchitect road on /Assets/Forest400mBaseTerrain that would be extremely appreciated! Thanks!

**Comment by embeddedt** [comment]
@anthonyromyn I downloaded your project and gave it a try. Unfortunately I wasn't able to reproduce the issue... not sure why.

I also just realized that there were some fixes that I never merged into my fork. I just applied those and pushed them to GitHub... could you give it another try?

If it still doesn't work I'll be happy to investigate further.

**Comment by anthonyromyn** [comment]
@embeddedt Thanks! I tried but same behaviour. One thing I noticed though is that the master fork at https://github.com/embeddedt/RoadArchitect says last commit was Feb 10th. Is that okay or am I using the wrong fork?

**Comment by embeddedt** [comment]
@anthonyromyn That commit is correct.

> I tried but same behaviour.

Hmm. There must be something in the steps you're following that I'm not doing. Here's what I did:

1. Make a new scene.
2. Create the road system (but not place the nodes yet).
3. Drag Forest400mBaseTerrain.asset into the scene view (makes the terrain).
4. Add the road on the terrain.
5. Add the concrete divider to the center of the road.

When I did that, I could switch between scenes without any issues and the road always appeared whenever I came back to the scene.

**Comment by anthonyromyn** [comment]
@embeddedt ah okay I see something new that I think is important: I was thinking I'd be able to save the road network + terrain as a prefab to then load into scenes, as opposed to saving the road network + terrain as a scene itself. When I save them as a scene, I get the same behaviour as you (things look good when I load that scene). It's when I try to save them as a prefab where this behaviour is occurring.

**Comment by embeddedt** [comment]
> save the road network + terrain as a prefab

That is your problem. You can't (easily) prefab the road network like you would with a standard Unity object.

**Comment by anthonyromyn** [comment]
@embeddedt Okay thanks so much for your help with this. You think I should use another road tool, then? If you have any recommendations I would be all ears!

**Comment by djohns451** [comment]
@anthonyromyn You're welcome to check the "Save Mesh Assets" button on the RoadSystem, if you are unable to create the roads programmatically. Once the mesh assets are saved, you just have to add instances of them to the Prefab objects you need.

**Comment by embeddedt** [comment]
@djohns451 Doesn't "Save mesh assets" have performance issues?

**Comment by djohns451** [comment]
It does, but that's only when the meshes are generated, as it has to spend time saving the meshes.

**Comment by djohns451** [comment]
The preferred way would be to use [GSDRoadAutomation.Create_Programmatically](https://github.com/MicroGSD/RoadArchitect/blob/master/GSDRoadAutomation.cs#L31) if in the editor.

[example](https://github.com/MicroGSD/RoadArchitect/blob/master/GSDUnitTests.cs#L349)

**Comment by djohns451** [comment]
However, if you are not instancing your roads in the Editor, you would need to save the mesh assets and add them to the prefabs.

**Comment by anthonyromyn** [comment]
@djohns451 @embeddedt Early returns on using save mesh assets looks like it will work great for what I need! Thank you both so much for your help!
