### ISSUE TITLE
No Intersections after drag over node [Unity 5.6.1f1]

### ISSUE THREAD

**Issue by truoss** [MicroGSD/RoadArchitect#7]
Hi, I added the unity package 1.6 to my project. Created a empty scene and run the "run all Unit tests" except one intersection everything looks right.

But when I add 2 roads and follow the #3 Intersection Tutorial, the node snaps but does not generate a intersection.

There is no error. Only two roads overlapping each other.

**Comment by TomOR1** [comment]
@truoss

Make sure that you are not using the end node of the road, or the start node. If you use them the road will just connect

**Comment by voblivion** [comment]
I confirm the issue, end node or not.

**Comment by djohns451** [comment]
Can't reproduce on this end.

**Comment by RayRay26** [comment]
I made a pull request #36 that I think will fix this problem. I was having this problem too until I found the commented-out line.

**Comment by embeddedt** [comment]
The pull request @RayRay26 made fixes this issue.
