### ISSUE TITLE
There is a shoulder option but no sidewalk?

### ISSUE THREAD

**Issue by theshinyknight** [MicroGSD/RoadArchitect#74]
Trying to add a sidewalk, but it seems that there is no option for doing so on the road node. 
Is there a specific option to add sidewalk? I would assume they can be added as side objects like barriers and lights, but I find strange that they are not part of the main set of assets?

**Comment by FritzsHero** [comment]
Hello @theshinyknight,

Yes, this is correct, currently there is no option to add sidewalks.
The best option for creating sidewalks currently, might be the edge objects or the extrusion objects.
I mark this as a feature suggestion for the future.

Best Regards,

Fritzs
