### ISSUE TITLE
Cannot install into Unity

### ISSUE THREAD

**Issue by Bokonon1st** [MicroGSD/RoadArchitect#75]
I am trying to install, I use assets>packages>install>install custom package.... everything seems to run fine and I can see RoadArchitect in my assets folder but I have no menu option to use RoadArchitect.
Am I missing something?

**Comment by embeddedt** [comment]
Sometimes you need to close and re-open Unity before it picks up on the menu option.

**Comment by Bokonon1st** [comment]
Started in again but still not there, thanks though.

**Comment by embeddedt** [comment]
Is the folder hierarchy exactly this: `<project root>/Assets/RoadArchitect`? If it's not named with the exact name of `RoadArchitect` I think there might be issues. 

If it still doesn't work, do [my fork](https://github.com/embeddedt/RoadArchitect) or [@FritzsHero's fork](https://github.com/FritzsHero/RoadArchitect) work?

**Comment by Bokonon1st** [comment]
Same result, losing hair now. I am new to this, I can't even get started. 
Assets/RoadArchitect is the file location.

**Comment by embeddedt** [comment]
Any errors in the console?

**Comment by FritzsHero** [comment]
Hello Bokonon1st,

what Unity version do you use?
To install RoadArchitect you just need to download the sources from the releases and unzip the RoadArchitect folder into your Assets directory.
If this does not work for you, could you please tell us which OS you use?

Best Regards

Fritzs

**Comment by Bokonon1st** [comment]
These are the errors that I get, I have been using the .unitypackage version. I will try unzipping instead if that can help.
I run Windows 10 64 bit and am up to date with windows updates for my sins.

![errors](https://user-images.githubusercontent.com/50710305/73489835-98306b00-43ab-11ea-83eb-9ae145cc8b5b.PNG)

**Comment by FritzsHero** [comment]
These warnings so far have nothing to do with RoadArchitect.
They are produced by your installed packages.
Could you clear your Console and/or only show errors of your project?
You can select to only display errors at the top right corner of the console window. (Deselecting Logs and WarningLogs)
If there are errors left, they might prevent compilation of your and the imported scripts, so please try to solve any compilation errors.

Best Regards

Fritzs

**Comment by embeddedt** [comment]
Definitely try downloading the ZIP from GitHub and unzipping that (and be sure to rename the folder to `RoadArchitect`, not `RoadArchitect-master`). The `unitypackage` version is getting older and I don't know if it works properly with newer versions of Unity.

**Comment by Bokonon1st** [comment]
> Definitely try downloading the ZIP from GitHub and unzipping that (and be sure to rename the folder to `RoadArchitect`, not `RoadArchitect-master`). The `unitypackage` version is getting older and I don't know if it works properly with newer versions of Unity.

Do I unzip into Assets folder?
Tried it, another guy from the Unity forum installed it using the same Unity version as me and posted a screen shot. Minutes!! I have been trying for days now to find a solution. I am a complete noob to Unity, but not to programming. I am used to days of frustration and hair pulling, until that eureka moment comes and I feel like God himself xD
Anyone finds my solution I will love you for all time lol.

**Comment by embeddedt** [comment]
Yes. After you unzip it the folder hierarchy should be like [what I mentioned above](https://github.com/MicroGSD/RoadArchitect/issues/75#issuecomment-580326010).

Did you try what @FritzsHero said (clear your console and only show errors)?

Did you try this in a fresh Unity project, or an existing one?

**Comment by Bokonon1st** [comment]
I have reinstalled Unity completely now, re-installed and now it works as it should. I didn't choose Android and iOS support options this time though. Maybe that was the issue. Thank you all for your time and support.
