### ISSUE TITLE
Road Architect For Offroad Environment

### ISSUE THREAD

**Issue by MuhammadWaqasOfficial** [MicroGSD/RoadArchitect#78]
Hi i use road architecture for my last game. its good to use it. Now I want to use it for offroad game. I wonder if features regarding offroad environment also added.
Regards
Muhammad Waqas

**Comment by FritzsHero** [comment]
Hello,

you can probably use the normal road system to create a offroad environment. Just switch the road textures with your offroad textures. Also you should be able to deactivate the shoulders of the road with the "Shoulders enabled:" option, if you prefer just the road.


Best Regards,

Fritzs
