### ISSUE TITLE
Clearing RS.Event_MouseTerrainHit is not qualified by event type [Unity 5.6.1xf1]

### ISSUE THREAD

**Issue by mneilly** [MicroGSD/RoadArchitect#8]
I'm using Unity 5.6.1xf1.

OnSceneGUI() sets RS.Editor_MouseTerrainHit based on control or shift being pressed while the current event is MouseMove or MouseDrag. 

```
if (current.control && (Event.current.type == EventType.MouseMove || Event.current.type == EventType.MouseDrag)) {
	Ray worldRay = HandleUtility.GUIPointToWorldRay (Event.current.mousePosition);
	RaycastHit hitInfo;
	if (Physics.Raycast (worldRay, out hitInfo)) {
		if (hitInfo.collider.transform.GetComponent<Terrain> () != null || hitInfo.collider.transform.name.ToLower ().Contains ("terrain")) {
			RS.Editor_MousePos = hitInfo.point;
			RS.Editor_MouseTerrainHit = true;
```

Then the following code block clears RS.Editor_MouseTerrainHit if neither control nor shift are pressed without be qualified against the event type. When layout and repaint events occur, RS.Editor_MouseTerrainHit is cleared and it is impossible to place nodes as a result.

The following change allows me to place nodes:

```
- if(!current.control && !current.shift){
+ if (!current.control && !current.shift && (Event.current.type == EventType.MouseMove || Event.current.type == EventType.MouseDrag)) {
```

**Comment by djohns451** [comment]
#17 Merged in.
