### ISSUE TITLE
Terrain deformation

### ISSUE THREAD

**Issue by gbagiryan** [MicroGSD/RoadArchitect#80]
Hi, first of all want to thank you for this asset, it is definetly the best one I could find. 
The issue I'm having is that I have an uneven terrain (which I made from a mesh with object2terrain script). So whenever i place a road the terrain doesn't rise with the road it seems like the asset considers not the surface of the terrain but the zero height point of it. Am I missing something? Also wherever I place a node it goes under the terrain so I have to raise them manually.
 Can you please help me solve it?

**Comment by FritzsHero** [comment]
Hello,

are you using the standard unity terrain? If yes, this should work. Maybe you need to manually assign a GSDTerrain to your Terrain in the Editor.


Best Regards

Fritzs

**Comment by marcell123455** [comment]
Try setting the position of the terrain to 0.0.0 and the road system also.
