### ISSUE TITLE
openstreetmap

### ISSUE THREAD

**Issue by rynex-zv** [MicroGSD/RoadArchitect#82]
hi , how can i import .osm / openstreetmap data ?

**Comment by embeddedt** [comment]
There is no feature for importing existing road networks at this time. You'll have to recreate the roads yourself.

You may be able to simplify the process by setting a Google Earth image or something similar as your terrain texture, but you would still need to place all the roads by hand - that would just give you a guide to place them by.

**Comment by rynex-zv** [comment]
ok , thanks!
do you know how can i add a crosswalk  ?
