### ISSUE TITLE
Manipulate via script

### ISSUE THREAD

**Issue by linwe2012** [MicroGSD/RoadArchitect#85]
Can I manipulate the roads via c# scripts. Do I have ro modify source code to do that? If modification is needed, could anyone give some hints on how to do it?

**Comment by FritzsHero** [comment]
Hello,

in the version 1.6 to 1.9 of RoadArchitect usage is basically limited to just inside the unity editor. Look into RoadAutomation for creation of roads by script in editor. These functions do not work in a build game. However I removed this limitation for version 2.0 of RoadArchitect. I am still working on 2.0 so I can not give any timing on when I will release 2.0 .
You should take a look at my fork which contains additional patches.

Best Regards,

Fritzs

**Comment by NikitaSavik** [comment]
Sorry for bumping this, just checking if there is an unlocked version somewhere?
Is it possible to build roads at a runtime right now?
