### ISSUE TITLE
Road is pink and no textures are put on

### ISSUE THREAD

**Issue by umayr-r** [MicroGSD/RoadArchitect#88]
https://www.youtube.com/watch?v=sS-qAdlID68

i was watching this tutorial
when he put the road down it automatically put the texture like a road
when i do it, it places a road. but its pink. i put a texture on it, it puts it in the middle
![image](https://user-images.githubusercontent.com/83378213/116484411-eb2ff100-a880-11eb-882c-ba8be943108f.png)

**Comment by embeddedt** [comment]
Please try [@FritzsHero's fork](https://github.com/FritzsHero/RoadArchitect) - this is a known bug with upstream RoadArchitect and newer versions of Unity.

**Comment by umayr-r** [comment]
> Please try [@FritzsHero's fork](https://github.com/FritzsHero/RoadArchitect) - this is a known bug with upstream RoadArchitect and newer versions of Unity.

so with the current asset i have, should i delete it and use this one? or is this an extension

**Comment by embeddedt** [comment]
You should delete this one and install the other one - it's a full replacement, not just an extension.
