### ISSUE TITLE
StreeLightDouble Edge Object Spawning Twice

### ISSUE THREAD

**Issue by Dannyfaction** [MicroGSD/RoadArchitect#9]
Hey there,

Very often when I spawn a StreetLightDouble Edge Object via the wizard or from script, it spawns the Streelight Twice. Sometimes twice on the same location and sometimes with an offset.

Thanks in advance.

**Comment by tonygod** [comment]
Hi @SkaterDanny, I have been unable to reproduce this, but maybe I am missing something specific to your configuration or use case.

I am using Unity 5.6.1f1 and 2017.1 and I have tried 2-lane and 4-lane roads.  Could you perhaps provide more details and a link to a video showing how you reproduce the problem?
