### ISSUE TITLE
Build standalone game

### ISSUE THREAD

**Issue by parvanehAghajani** [MicroGSD/RoadArchitect#90]
Hello, 

I have used RoadArchitect to create road network in runtime using script. 
I need to build all roads when the player starts the game, but I am getting build error because of UNITY_EDITOR! Is there anyway to change the source code to build standalone game? 
Or is there any patch to support this?

Thank you

**Comment by embeddedt** [comment]
Upstream RoadArchitect does not support building roads at runtime and likely never will.

However, I think @FritzsHero may have been working on this functionality in his [fork](https://github.com/FritzsHero/RoadArchitect).

**Comment by djohns451** [comment]
I have write access to this repository, and I'm certainly willing to merge
in PRs, but don't have time for much else myself.
