### ISSUE TITLE
Road Architect materials not working in Unity 2020 PC

### ISSUE THREAD

**Issue by oeyXD** [MicroGSD/RoadArchitect#91]
So I'm working on a game about action/adventure, shooter, open world genre of game and when creating roads using the Road Architect and what I come across is something like this:

![image](https://user-images.githubusercontent.com/89714220/131326345-2e1d6a74-cd05-4342-8f56-7e6db6001b07.png)

And I don't understand what is happening or why this is happening. And I already tried to tweak some settings in the .Mat file to see if there are some textures and normals linked and indeed, there are. But I removed them and put them back and still nothing changed. 

I don't know if Unity itself is creating the problem or the files of Road Architect, or both.

Additional Info: I'm on an HDRI project.

**Comment by embeddedt** [comment]
Probably the same issue as #88.

**Comment by oeyXD** [comment]
For those who have the same problem, the solution might be this:

Go to a material and set the Shader to HDRP/Lit, if you're in a HDRP project.

**Comment by djohns451** [comment]
There is also an HDRP branch (a bit out of date, but it should update fine)
for this case, which should be in my fork.
